### ISSUE TITLE
How to  use this kernel with Azure Data Studio ?

### ISSUE THREAD

**Issue by datauduong** [Hourout/mysql_kernel#1]
Currently, Microsoft Azure Data Studio Support MS SQL, can this Kernel be used with Azure Data Studio.
If yes, can you please show me how in Jupyter Notebook.

Thank you.

**Comment by Hourout** [comment]
Hi, Have you tried it according to the installation steps of the homepage readme?

I have never used Azure Data Studio as a platform

**Comment by datauduong** [comment]
I have followed the step on the homepage, It does not show up in the Kernel listing in Azure Data Studio or Visual Studio Code

**Comment by Hourout** [comment]
This project is to provide a mysql kernel for jupyter notebook, I am not sure whether it can be used normally in Azure Data Studio or Visual Studio Code, and I have not tested it.

On the other hand, I have not used tools such as Azure Data Studio or Visual Studio Code, which is not fashionable. Haha

**Comment by datauduong** [comment]
No worry Hourout, It is fascinating to see Jupyter enable us with better information sharing and documenting.
