### ISSUE TITLE
"must be real number, not dict"?

### ISSUE THREAD

**Issue by 71walceli** [Hourout/mysql_kernel#2]
I seem to have some problem doind following query:

```sql
SELECT 
    productName
    FROM products
    WHERE productName LIKE '%Ferrari%'
;
```

Output: `must be real number, not dict`

But I get a very strange output as shown above, whereas im sysql prompt, I do get expected result:

```
mysql> SELECT 
    ->     productName
    ->     FROM products
    ->     WHERE productName LIKE '%Ferrari%'
    -> ;
+-----------------------------+
| productName                 |
+-----------------------------+
| 2001 Ferrari Enzo           |
| 1992 Ferrari 360 Spider red |
+-----------------------------+
2 rows in set (0.01 sec)
```

so I think it's a bug.

I attach links to the following:
- i'm using this sample DB: https://www.mysqltutorial.org/wp-content/uploads/2018/03/mysqlsampledatabase.zip. 
- My notebook: https://mega.nz/file/IkYESR5Z#CVuS3dsAMRtNSSiJiLW4YKLFaKmOKcLRndk56J5GrKM.

Thanks in advance for your attention.

**Comment by Hourout** [comment]
Please uninstall and reinstall the latest version 0.4.1 to see if there are any problems

**Comment by Hourout** [comment]
SELECT productName FROM products WHERE productName LIKE '%%Ferrari%%';
